class AnimationFeatures:

    def __init__(self) -> None:
        pass

    #   REPLACE BACKGROUND 

    #   CENSOR IMAGE 

    #   REMOVE IMAGE CENSORSHIP 

    #   GENERATE CHARACTER SHEET 

    #   GENERATE IMAGES BASED OF CHARACTER SHEET 

    #   RETURN VIDEO FRAMES WITH BACKGROUND 

    #   RETURN VIDEO FRAMES WITHOUT BACKGROUND 

    #   RETURN VIDEO FRAMES WITH BACKGROUND REPLACED 
